version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      dart-dependencies:
        patterns: ['*']
        update-types: [minor, patch]

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
